server:
  port: 1999

spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:file:~/spring-session-jdbc
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""
  flyway:
    url: jdbc:h2:file:~/spring-session-jdbc
    userEntity: "sa"
    password: ""
    locations: classpath:db/migrations
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
